//-------------------------------------------------------------------------
//FILE GENERATED BY ICS MANAGER FROM SCHEMA 'PluginManager' DON'T MODIFY IT;
//-------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using DatalayerCs;

namespace OrmCs
{
	public class YXsysPfeatures : Yyy
	{
		public YXsysPfeatures() { construct("XSYS_PFEATURES", null); }
		public YXsysPfeatures(OrmLinker lk) { construct("XSYS_PFEATURES", lk); }
		public int m_id { get { return getInt(0); } set { setInt(0, value); } }
		public DatPtr z_id { get { return new DatPtr(this, 0); } }
		public string m_plugin_name { get { return getString(1); } set { setString(1, 255, value); } }
		public DatPtr z_plugin_name { get { return new DatPtr(this, 1); } }
		public string m_feature_name { get { return getString(2); } set { setString(2, 255, value); } }
		public DatPtr z_feature_name { get { return new DatPtr(this, 2); } }
		public int m_enable { get { return getInt(3); } set { setInt(3, value); } }
		public DatPtr z_enable { get { return new DatPtr(this, 3); } }
		public string m_settings { get { return getString(4); } set { setString(4, 255, value); } }
		public DatPtr z_settings { get { return new DatPtr(this, 4); } }
		public string m_description { get { return getString(5); } set { setString(5, 255, value); } }
		public DatPtr z_description { get { return new DatPtr(this, 5); } }
		public string m_cust_txt1 { get { return getString(6); } set { setString(6, 255, value); } }
		public DatPtr z_cust_txt1 { get { return new DatPtr(this, 6); } }
		public string m_cust_txt2 { get { return getString(7); } set { setString(7, 255, value); } }
		public DatPtr z_cust_txt2 { get { return new DatPtr(this, 7); } }
		public string m_cust_txt3 { get { return getString(8); } set { setString(8, 255, value); } }
		public DatPtr z_cust_txt3 { get { return new DatPtr(this, 8); } }
		public DateTime m_cust_dat1 { get { return getDateTime(9); } set { setDateTime(9, value); } }
		public DatPtr z_cust_dat1 { get { return new DatPtr(this, 9); } }
		public DateTime m_cust_dat2 { get { return getDateTime(10); } set { setDateTime(10, value); } }
		public DatPtr z_cust_dat2 { get { return new DatPtr(this, 10); } }
		public int m_cust_chb1 { get { return getInt(11); } set { setInt(11, value); } }
		public DatPtr z_cust_chb1 { get { return new DatPtr(this, 11); } }
		public int m_cust_chb2 { get { return getInt(12); } set { setInt(12, value); } }
		public DatPtr z_cust_chb2 { get { return new DatPtr(this, 12); } }
		public int m_cust_chb3 { get { return getInt(13); } set { setInt(13, value); } }
		public DatPtr z_cust_chb3 { get { return new DatPtr(this, 13); } }
		public YXsysPfRights m_Plugins_rights { get { return (YXsysPfRights)getYyy(14); } set { setYyy(14, value); } }
	}

	public class YXsysPfRights : Yyy
	{
		public YXsysPfRights() { construct("XSYS_PF_RIGHTS", null); }
		public YXsysPfRights(OrmLinker lk) { construct("XSYS_PF_RIGHTS", lk); }
		public int m_sys_pfeatures_id { get { return getInt(0); } set { setInt(0, value); } }
		public DatPtr z_sys_pfeatures_id { get { return new DatPtr(this, 0); } }
		public YXsysPfeatures m_Plugin_Feature { get { return (YXsysPfeatures)getYyy(1); } set { setYyy(1, value); } }
		public int m_taskforce_id { get { return getInt(2); } set { setInt(2, value); } }
		public DatPtr z_taskforce_id { get { return new DatPtr(this, 2); } }
		public YTaskforce m_Taskforce { get { return (YTaskforce)getYyy(3); } set { setYyy(3, value); } }
		public string m_description { get { return getString(4); } set { setString(4, 255, value); } }
		public DatPtr z_description { get { return new DatPtr(this, 4); } }
		public string m_cust_txt1 { get { return getString(5); } set { setString(5, 255, value); } }
		public DatPtr z_cust_txt1 { get { return new DatPtr(this, 5); } }
		public string m_cust_txt2 { get { return getString(6); } set { setString(6, 255, value); } }
		public DatPtr z_cust_txt2 { get { return new DatPtr(this, 6); } }
		public string m_cust_txt3 { get { return getString(7); } set { setString(7, 255, value); } }
		public DatPtr z_cust_txt3 { get { return new DatPtr(this, 7); } }
		public DateTime m_cust_dat1 { get { return getDateTime(8); } set { setDateTime(8, value); } }
		public DatPtr z_cust_dat1 { get { return new DatPtr(this, 8); } }
		public DateTime m_cust_dat2 { get { return getDateTime(9); } set { setDateTime(9, value); } }
		public DatPtr z_cust_dat2 { get { return new DatPtr(this, 9); } }
		public int m_cust_chb1 { get { return getInt(10); } set { setInt(10, value); } }
		public DatPtr z_cust_chb1 { get { return new DatPtr(this, 10); } }
		public int m_cust_chb2 { get { return getInt(11); } set { setInt(11, value); } }
		public DatPtr z_cust_chb2 { get { return new DatPtr(this, 11); } }
		public int m_cust_chb3 { get { return getInt(12); } set { setInt(12, value); } }
		public DatPtr z_cust_chb3 { get { return new DatPtr(this, 12); } }
	}

}
