//-------------------------------------------------------------------------
//FILE GENERATED BY ICS MANAGER FROM SCHEMA 'TicketSystem' DON'T MODIFY IT;
//-------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace OrmCs
{
	public class YXticketTasks : Yyy
	{
		public YXticketTasks() { construct("XTICKET_TASKS", null); }
		public YXticketTasks(OrmLinker lk) { construct("XTICKET_TASKS", lk); }
		public int m_id { get { return getInt(0); } set { setInt(0, value); } }
		public DatPtr z_id { get { return new DatPtr(this, 0); } }
		public int m_ticket_id { get { return getInt(1); } set { setInt(1, value); } }
		public DatPtr z_ticket_id { get { return new DatPtr(this, 1); } }
		public YXticketTickets m_Ticket { get { return (YXticketTickets)getYyy(2); } set { setYyy(2, value); } }
		public string m_type { get { return getString(3); } set { setString(3, 250, value); } }
		public DatPtr z_type { get { return new DatPtr(this, 3); } }
		public string m_status { get { return getString(4); } set { setString(4, 250, value); } }
		public DatPtr z_status { get { return new DatPtr(this, 4); } }
		public string m_details { get { return getString(5); } set { setString(5, 5000, value); } }
		public DatPtr z_details { get { return new DatPtr(this, 5); } }
		public int m_assigned_to_id { get { return getInt(6); } set { setInt(6, value); } }
		public DatPtr z_assigned_to_id { get { return new DatPtr(this, 6); } }
		public string m_assigned_to_table { get { return getString(7); } set { setString(7, 50, value); } }
		public DatPtr z_assigned_to_table { get { return new DatPtr(this, 7); } }
		public DateTime m_date_created { get { return getDateTime(8); } set { setDateTime(8, value); } }
		public DatPtr z_date_created { get { return new DatPtr(this, 8); } }
		public string m_created_by { get { return getString(9); } set { setString(9, 30, value); } }
		public DatPtr z_created_by { get { return new DatPtr(this, 9); } }
		public DateTime m_date_modified { get { return getDateTime(10); } set { setDateTime(10, value); } }
		public DatPtr z_date_modified { get { return new DatPtr(this, 10); } }
		public string m_modified_by { get { return getString(11); } set { setString(11, 30, value); } }
		public DatPtr z_modified_by { get { return new DatPtr(this, 11); } }
	}

	public class YXticketTickets : Yyy
	{
		public YXticketTickets() { construct("XTICKET_TICKETS", null); }
		public YXticketTickets(OrmLinker lk) { construct("XTICKET_TICKETS", lk); }
		public int m_id { get { return getInt(0); } set { setInt(0, value); } }
		public DatPtr z_id { get { return new DatPtr(this, 0); } }
		public string m_title { get { return getString(1); } set { setString(1, 250, value); } }
		public DatPtr z_title { get { return new DatPtr(this, 1); } }
		public string m_type { get { return getString(2); } set { setString(2, 250, value); } }
		public DatPtr z_type { get { return new DatPtr(this, 2); } }
		public string m_category { get { return getString(3); } set { setString(3, 250, value); } }
		public DatPtr z_category { get { return new DatPtr(this, 3); } }
		public string m_subcategory { get { return getString(4); } set { setString(4, 250, value); } }
		public DatPtr z_subcategory { get { return new DatPtr(this, 4); } }
		public string m_status { get { return getString(5); } set { setString(5, 250, value); } }
		public DatPtr z_status { get { return new DatPtr(this, 5); } }
		public string m_details { get { return getString(6); } set { setString(6, 5000, value); } }
		public DatPtr z_details { get { return new DatPtr(this, 6); } }
		public string m_response { get { return getString(7); } set { setString(7, 5000, value); } }
		public DatPtr z_response { get { return new DatPtr(this, 7); } }
		public int m_knowledge_id { get { return getInt(8); } set { setInt(8, value); } }
		public DatPtr z_knowledge_id { get { return new DatPtr(this, 8); } }
		public YXticketKnowdb m_KnowledgeDatabase { get { return (YXticketKnowdb)getYyy(9); } set { setYyy(9, value); } }
		public int m_assigned_to_id { get { return getInt(10); } set { setInt(10, value); } }
		public DatPtr z_assigned_to_id { get { return new DatPtr(this, 10); } }
		public string m_assigned_to_table { get { return getString(11); } set { setString(11, 50, value); } }
		public DatPtr z_assigned_to_table { get { return new DatPtr(this, 11); } }
		public int m_requested_by_id { get { return getInt(12); } set { setInt(12, value); } }
		public DatPtr z_requested_by_id { get { return new DatPtr(this, 12); } }
		public string m_requested_by_table { get { return getString(13); } set { setString(13, 50, value); } }
		public DatPtr z_requested_by_table { get { return new DatPtr(this, 13); } }
		public int m_requested_for_id { get { return getInt(14); } set { setInt(14, value); } }
		public DatPtr z_requested_for_id { get { return new DatPtr(this, 14); } }
		public string m_requested_for_table { get { return getString(15); } set { setString(15, 50, value); } }
		public DatPtr z_requested_for_table { get { return new DatPtr(this, 15); } }
		public DateTime m_date_created { get { return getDateTime(16); } set { setDateTime(16, value); } }
		public DatPtr z_date_created { get { return new DatPtr(this, 16); } }
		public string m_created_by { get { return getString(17); } set { setString(17, 30, value); } }
		public DatPtr z_created_by { get { return new DatPtr(this, 17); } }
		public DateTime m_date_modified { get { return getDateTime(18); } set { setDateTime(18, value); } }
		public DatPtr z_date_modified { get { return new DatPtr(this, 18); } }
		public string m_modified_by { get { return getString(19); } set { setString(19, 30, value); } }
		public DatPtr z_modified_by { get { return new DatPtr(this, 19); } }
	}

	public class YXticketKnowdb : Yyy
	{
		public YXticketKnowdb() { construct("XTICKET_KNOWDB", null); }
		public YXticketKnowdb(OrmLinker lk) { construct("XTICKET_KNOWDB", lk); }
		public int m_id { get { return getInt(0); } set { setInt(0, value); } }
		public DatPtr z_id { get { return new DatPtr(this, 0); } }
		public string m_subject { get { return getString(1); } set { setString(1, 250, value); } }
		public DatPtr z_subject { get { return new DatPtr(this, 1); } }
		public string m_status { get { return getString(2); } set { setString(2, 250, value); } }
		public DatPtr z_status { get { return new DatPtr(this, 2); } }
		public string m_table_name { get { return getString(3); } set { setString(3, 250, value); } }
		public DatPtr z_table_name { get { return new DatPtr(this, 3); } }
		public string m_topic { get { return getString(4); } set { setString(4, 5000, value); } }
		public DatPtr z_topic { get { return new DatPtr(this, 4); } }
		public DateTime m_date_created { get { return getDateTime(5); } set { setDateTime(5, value); } }
		public DatPtr z_date_created { get { return new DatPtr(this, 5); } }
		public string m_created_by { get { return getString(6); } set { setString(6, 30, value); } }
		public DatPtr z_created_by { get { return new DatPtr(this, 6); } }
		public DateTime m_date_modified { get { return getDateTime(7); } set { setDateTime(7, value); } }
		public DatPtr z_date_modified { get { return new DatPtr(this, 7); } }
		public string m_modified_by { get { return getString(8); } set { setString(8, 30, value); } }
		public DatPtr z_modified_by { get { return new DatPtr(this, 8); } }
	}

	public class YXticketMessages : Yyy
	{
		public YXticketMessages() { construct("XTICKET_MESSAGES", null); }
		public YXticketMessages(OrmLinker lk) { construct("XTICKET_MESSAGES", lk); }
		public int m_id { get { return getInt(0); } set { setInt(0, value); } }
		public DatPtr z_id { get { return new DatPtr(this, 0); } }
		public int m_ticket_id { get { return getInt(1); } set { setInt(1, value); } }
		public DatPtr z_ticket_id { get { return new DatPtr(this, 1); } }
		public YXticketTickets m_Ticket { get { return (YXticketTickets)getYyy(2); } set { setYyy(2, value); } }
		public int m_message_from_id { get { return getInt(3); } set { setInt(3, value); } }
		public DatPtr z_message_from_id { get { return new DatPtr(this, 3); } }
		public string m_message_from_table { get { return getString(4); } set { setString(4, 50, value); } }
		public DatPtr z_message_from_table { get { return new DatPtr(this, 4); } }
		public int m_message_to_id { get { return getInt(5); } set { setInt(5, value); } }
		public DatPtr z_message_to_id { get { return new DatPtr(this, 5); } }
		public string m_message_to_table { get { return getString(6); } set { setString(6, 50, value); } }
		public DatPtr z_message_to_table { get { return new DatPtr(this, 6); } }
		public string m_message { get { return getString(7); } set { setString(7, 5000, value); } }
		public DatPtr z_message { get { return new DatPtr(this, 7); } }
		public DateTime m_date_created { get { return getDateTime(8); } set { setDateTime(8, value); } }
		public DatPtr z_date_created { get { return new DatPtr(this, 8); } }
		public string m_created_by { get { return getString(9); } set { setString(9, 30, value); } }
		public DatPtr z_created_by { get { return new DatPtr(this, 9); } }
		public DateTime m_date_modified { get { return getDateTime(10); } set { setDateTime(10, value); } }
		public DatPtr z_date_modified { get { return new DatPtr(this, 10); } }
		public string m_modified_by { get { return getString(11); } set { setString(11, 30, value); } }
		public DatPtr z_modified_by { get { return new DatPtr(this, 11); } }
	}

}
