//-------------------------------------------------------------------------
//FILE GENERATED BY ICS MANAGER FROM SCHEMA 'MiscTools' DON'T MODIFY IT;
//-------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace OrmCs
{
	public class YXmiscQuerystore : Yyy
	{
		public YXmiscQuerystore() { construct("XMISC_QUERYSTORE", null); }
		public YXmiscQuerystore(OrmLinker lk) { construct("XMISC_QUERYSTORE", lk); }
		public int m_id { get { return getInt(0); } set { setInt(0, value); } }
		public DatPtr z_id { get { return new DatPtr(this, 0); } }
		public string m_name { get { return getString(1); } set { setString(1, 250, value); } }
		public DatPtr z_name { get { return new DatPtr(this, 1); } }
		public string m_type { get { return getString(2); } set { setString(2, 250, value); } }
		public DatPtr z_type { get { return new DatPtr(this, 2); } }
		public string m_table_name { get { return getString(3); } set { setString(3, 250, value); } }
		public DatPtr z_table_name { get { return new DatPtr(this, 3); } }
		public string m_description { get { return getString(4); } set { setString(4, 5000, value); } }
		public DatPtr z_description { get { return new DatPtr(this, 4); } }
		public string m_itemstore { get { return getString(5); } set { setString(5, 8000, value); } }
		public DatPtr z_itemstore { get { return new DatPtr(this, 5); } }
		public string m_engine { get { return getString(6); } set { setString(6, 1000, value); } }
		public DatPtr z_engine { get { return new DatPtr(this, 6); } }
		public DateTime m_date_created { get { return getDateTime(7); } set { setDateTime(7, value); } }
		public DatPtr z_date_created { get { return new DatPtr(this, 7); } }
		public string m_created_by { get { return getString(8); } set { setString(8, 30, value); } }
		public DatPtr z_created_by { get { return new DatPtr(this, 8); } }
		public DateTime m_date_modified { get { return getDateTime(9); } set { setDateTime(9, value); } }
		public DatPtr z_date_modified { get { return new DatPtr(this, 9); } }
		public string m_modified_by { get { return getString(10); } set { setString(10, 30, value); } }
		public DatPtr z_modified_by { get { return new DatPtr(this, 10); } }
	}

	public class YXmiscTranslations : Yyy
	{
		public YXmiscTranslations() { construct("XMISC_TRANSLATIONS", null); }
		public YXmiscTranslations(OrmLinker lk) { construct("XMISC_TRANSLATIONS", lk); }
		public int m_id { get { return getInt(0); } set { setInt(0, value); } }
		public DatPtr z_id { get { return new DatPtr(this, 0); } }
		public int m_impop_id { get { return getInt(1); } set { setInt(1, value); } }
		public DatPtr z_impop_id { get { return new DatPtr(this, 1); } }
		public YImportOp m_Import_Operations { get { return (YImportOp)getYyy(2); } set { setYyy(2, value); } }
		public string m_lang { get { return getString(3); } set { setString(3, 50, value); } }
		public DatPtr z_lang { get { return new DatPtr(this, 3); } }
		public string m_from_string { get { return getString(4); } set { setString(4, 255, value); } }
		public DatPtr z_from_string { get { return new DatPtr(this, 4); } }
		public string m_to_string { get { return getString(5); } set { setString(5, 255, value); } }
		public DatPtr z_to_string { get { return new DatPtr(this, 5); } }
		public int m_isfromstrings { get { return getInt(6); } set { setInt(6, value); } }
		public DatPtr z_isfromstrings { get { return new DatPtr(this, 6); } }
		public int m_isobsolete { get { return getInt(7); } set { setInt(7, value); } }
		public DatPtr z_isobsolete { get { return new DatPtr(this, 7); } }
		public int m_iscustomf { get { return getInt(8); } set { setInt(8, value); } }
		public DatPtr z_iscustomf { get { return new DatPtr(this, 8); } }
	}

}
